# -*- coding: utf-8 -*-

DEBUG = True
ASSETS_DEBUG = DEBUG

SECRET_KEY = 'SECRET_KEY'
WTF_CSRF_SECRET_KEY = 'WTF_CSRF_SECRET_KEY'

SQLALCHEMY_ECHO = DEBUG
SQLALCHEMY_DATABASE_URI = 'sqlite:///tmp.db'
